"""add_jsonb_propertiesa

Revision ID: fa33501cf74e
Revises: 0b8e3b22a51c
Create Date: 2026-07-25 18:18:15.239458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa33501cf74e'
down_revision: Union[str, Sequence[str], None] = '0b8e3b22a51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ksm_items', sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ksm_items', sa.Column('schema_version', sa.Integer(), nullable=True))
    op.add_column('ksm_items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('ksm_items', 'item_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('ksm_items', 'subtype',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_ksm_items_angle'), table_name='ksm_items')
    op.drop_index(op.f('ix_ksm_items_climate_version'), table_name='ksm_items')
    op.drop_index(op.f('ix_ksm_items_dn'), table_name='ksm_items')
    op.drop_index(op.f('ix_ksm_items_medium'), table_name='ksm_items')
    op.drop_index(op.f('ix_ksm_items_pressure'), table_name='ksm_items')
    op.drop_index(op.f('ix_ksm_items_steel_grade'), table_name='ksm_items')
    op.drop_index(op.f('ix_ksm_items_strength_class'), table_name='ksm_items')
    op.create_index('idx_ksm_item_type', 'ksm_items', ['item_type'], unique=False)
    op.create_index('idx_ksm_properties_gin', 'ksm_items', ['properties'], unique=False, postgresql_using='gin')
    op.drop_column('ksm_items', 'gost_or_tu')
    op.drop_column('ksm_items', 'pressure')
    op.drop_column('ksm_items', 'wall_thickness')
    op.drop_column('ksm_items', 'inner_coating')
    op.drop_column('ksm_items', 'outer_coating')
    op.drop_column('ksm_items', 'angle')
    op.drop_column('ksm_items', 'medium')
    op.drop_column('ksm_items', 'steel_grade')
    op.drop_column('ksm_items', 'strength_class')
    op.drop_column('ksm_items', 'dn')
    op.drop_column('ksm_items', 'climate_version')
    op.add_column('mtr_items', sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('mtr_items', sa.Column('schema_version', sa.Integer(), nullable=True))
    op.add_column('mtr_items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('mtr_items', 'item_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('mtr_items', 'subtype',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('idx_mtr_items_dn_angle'), table_name='mtr_items')
    op.drop_index(op.f('idx_mtr_items_type_dn'), table_name='mtr_items')
    op.drop_index(op.f('ix_mtr_items_angle'), table_name='mtr_items')
    op.drop_index(op.f('ix_mtr_items_climate_version'), table_name='mtr_items')
    op.drop_index(op.f('ix_mtr_items_dn'), table_name='mtr_items')
    op.drop_index(op.f('ix_mtr_items_medium'), table_name='mtr_items')
    op.drop_index(op.f('ix_mtr_items_pressure'), table_name='mtr_items')
    op.drop_index(op.f('ix_mtr_items_steel_grade'), table_name='mtr_items')
    op.drop_index(op.f('ix_mtr_items_strength_class'), table_name='mtr_items')
    op.create_index('idx_mtr_item_type', 'mtr_items', ['item_type'], unique=False)
    op.create_index('idx_mtr_properties_gin', 'mtr_items', ['properties'], unique=False, postgresql_using='gin')
    op.drop_column('mtr_items', 'strength_class')
    op.drop_column('mtr_items', 'gost_or_tu')
    op.drop_column('mtr_items', 'pressure')
    op.drop_column('mtr_items', 'wall_thickness')
    op.drop_column('mtr_items', 'inner_coating')
    op.drop_column('mtr_items', 'outer_coating')
    op.drop_column('mtr_items', 'angle')
    op.drop_column('mtr_items', 'medium')
    op.drop_column('mtr_items', 'steel_grade')
    op.drop_column('mtr_items', 'd2')
    op.drop_column('mtr_items', 'd1')
    op.drop_column('mtr_items', 'dn')
    op.drop_column('mtr_items', 'climate_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mtr_items', sa.Column('climate_version', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('dn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('d1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('d2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('steel_grade', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('medium', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('angle', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('outer_coating', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('inner_coating', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('wall_thickness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('pressure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('gost_or_tu', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('mtr_items', sa.Column('strength_class', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_index('idx_mtr_properties_gin', table_name='mtr_items', postgresql_using='gin')
    op.drop_index('idx_mtr_item_type', table_name='mtr_items')
    op.create_index(op.f('ix_mtr_items_strength_class'), 'mtr_items', ['strength_class'], unique=False)
    op.create_index(op.f('ix_mtr_items_steel_grade'), 'mtr_items', ['steel_grade'], unique=False)
    op.create_index(op.f('ix_mtr_items_pressure'), 'mtr_items', ['pressure'], unique=False)
    op.create_index(op.f('ix_mtr_items_medium'), 'mtr_items', ['medium'], unique=False)
    op.create_index(op.f('ix_mtr_items_dn'), 'mtr_items', ['dn'], unique=False)
    op.create_index(op.f('ix_mtr_items_climate_version'), 'mtr_items', ['climate_version'], unique=False)
    op.create_index(op.f('ix_mtr_items_angle'), 'mtr_items', ['angle'], unique=False)
    op.create_index(op.f('idx_mtr_items_type_dn'), 'mtr_items', ['item_type', 'dn'], unique=False)
    op.create_index(op.f('idx_mtr_items_dn_angle'), 'mtr_items', ['dn', 'angle'], unique=False)
    op.alter_column('mtr_items', 'subtype',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('mtr_items', 'item_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('mtr_items', 'updated_at')
    op.drop_column('mtr_items', 'schema_version')
    op.drop_column('mtr_items', 'properties')
    op.add_column('ksm_items', sa.Column('climate_version', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('ksm_items', sa.Column('dn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ksm_items', sa.Column('strength_class', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('ksm_items', sa.Column('steel_grade', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('ksm_items', sa.Column('medium', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('ksm_items', sa.Column('angle', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ksm_items', sa.Column('outer_coating', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ksm_items', sa.Column('inner_coating', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ksm_items', sa.Column('wall_thickness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ksm_items', sa.Column('pressure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ksm_items', sa.Column('gost_or_tu', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index('idx_ksm_properties_gin', table_name='ksm_items', postgresql_using='gin')
    op.drop_index('idx_ksm_item_type', table_name='ksm_items')
    op.create_index(op.f('ix_ksm_items_strength_class'), 'ksm_items', ['strength_class'], unique=False)
    op.create_index(op.f('ix_ksm_items_steel_grade'), 'ksm_items', ['steel_grade'], unique=False)
    op.create_index(op.f('ix_ksm_items_pressure'), 'ksm_items', ['pressure'], unique=False)
    op.create_index(op.f('ix_ksm_items_medium'), 'ksm_items', ['medium'], unique=False)
    op.create_index(op.f('ix_ksm_items_dn'), 'ksm_items', ['dn'], unique=False)
    op.create_index(op.f('ix_ksm_items_climate_version'), 'ksm_items', ['climate_version'], unique=False)
    op.create_index(op.f('ix_ksm_items_angle'), 'ksm_items', ['angle'], unique=False)
    op.alter_column('ksm_items', 'subtype',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('ksm_items', 'item_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('ksm_items', 'updated_at')
    op.drop_column('ksm_items', 'schema_version')
    op.drop_column('ksm_items', 'properties')
    # ### end Alembic commands ###
